### ISSUE TITLE
Does not work with non-signed certificates and HTTPS

### ISSUE THREAD

**Issue by EpicLPer** [tobimori/streamdeck-homeassistant#1]
If I use the local hostname (SSL enabled, ex. https://myesxiserver:8123) without a properly signed certificate the plugin will refuse to do anything, however if I use the address that's reachable from outside (ex. https://ha.mydomainname.net) with a properly signed Let's Encrypt certificate it'll work without any issues.

Please make it so it'll also accept calls to domains with unsigned certs.

**Comment by tobimori** [comment]
This sadly is unfixable for me, as I'm using the javascript engine of the Stream Deck software. The Stream Deck software's browser needs to allow this.
