### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by ItMeCorban** [tobimori/streamdeck-homeassistant#4]
Just installed this and trying to get it working but I think my issue is with the formatting when adding the button in the stream deck - any chance of a screenshot or brief quick start guide?

**Comment by tobimori** [comment]
Hi,
with which property do you actually have a problem with?

**Comment by ItMeCorban** [comment]
at the moment I'm trying to setup a simple toggle - see below for how I've done it
![image](https://user-images.githubusercontent.com/13917133/83632154-ab8c5680-a596-11ea-8801-e7fbee4fc92b.png)

**Comment by tobimori** [comment]
Weird, that should be correct.

**Comment by ItMeCorban** [comment]
should I leave the https:// in for the address?

**Comment by tobimori** [comment]
Do you have a self signed certificate?

**Comment by ItMeCorban** [comment]
self signed though lets encrypt yea

**Comment by tobimori** [comment]
Let's Encrypt is different from a self signed certifcate. A Let's Encrypt certificate is trusted by all common browsers, a self signed certificate isn't. Do you need to install a certficate when going on your instance (over https) with a new browser? Is there some pop up like "This connection is not secure"?

**Comment by tobimori** [comment]
Also, can you please follow the directions specified [here](https://developer.elgato.com/documentation/stream-deck/sdk/create-your-own-plugin/#debugging-your-javascript-plugin) and check the output of the logs when pressing the button?

**Comment by ItMeCorban** [comment]
ah okay - not self signed then
Should I be seeing log files for the plugin?
![image](https://user-images.githubusercontent.com/13917133/83632895-f65a9e00-a597-11ea-9a94-e809af0b16f6.png)

all that's in the latest log file relating to the plugin is 
12:03:10.987                     StreamDeck                        main():                                         C:\Users\corba\Downloads\de.tobimori.streamdeck.homeassistant-v1.0.streamDeckPlugin

**Comment by tobimori** [comment]
No. The plugin is not producing log files. Please follow the linked Debugging guide and check if there is any error.

**Comment by ItMeCorban** [comment]
![image](https://user-images.githubusercontent.com/13917133/83633446-e0011200-a598-11ea-8b15-e0bed8532981.png)

**Comment by tobimori** [comment]
Seems like there is something wrong with your request then. Weird. Have you tried sending the message without service data?

**Comment by ItMeCorban** [comment]
same error if I take out the service data - I don't need to enable anything on the home assistant side do I? I used the same formatting before with ifttt but it's been a while since and I've reinstalled home assistant since

**Comment by tobimori** [comment]
if the frontend component is enabled it'd work

**Comment by ItMeCorban** [comment]
very strange. deleted and remade the button and it's working now...

**Comment by tobimori** [comment]
maybe you left a space somewhere :)

**Comment by MCManiac52** [comment]
just recreated the button again and the errors back, not sure whats going on
![image](https://user-images.githubusercontent.com/13917133/83635854-d5e11280-a59c-11ea-85f8-07c979c674de.png)
![image](https://user-images.githubusercontent.com/13917133/83635922-f315e100-a59c-11ea-8a2b-d811f9da4cf5.png)

**Comment by tobimori** [comment]
hi, please regenerate your access key :)

this time the mistake was that you wrote light.toggle instead of just toggle

**Comment by ItMeCorban** [comment]
ah okay got it now, thanks again! Think it's time for a coffee
