### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by warrendt** [tobimori/streamdeck-homeassistant#6]
Hi there, 

Is there a place I can check the logs for the request being sent ? 
I would like to troubleshoot why my calls aren't working

**Comment by tobimori** [comment]
Hi,
check out the [Elgato docs](https://developer.elgato.com/documentation/stream-deck/sdk/create-your-own-plugin/#debugging-your-javascript-plugin).

**Comment by warrendt** [comment]
> Hi,
> 
> check out the [Elgato docs](https://developer.elgato.com/documentation/stream-deck/sdk/create-your-own-plugin/#debugging-your-javascript-plugin).

Legend, thank you :) I was able to fix my issue. Thanks for the time and the plug-in.
